### ISSUE TITLE
html css lint error

### ISSUE THREAD

**Issue by superlbr** [vue-mini/create-vue-mini#1]
新的template是html，而不是wxml，语法会是个问题。比如这样
![image](https://github.com/vue-mini/create-vue-mini/assets/8142164/5bedcdbe-d8ff-4fad-8722-611d6b441480)

**Comment by yangmingshan** [comment]
使用 html 是为了无缝使用 prettier 等工具，这些报错是 vscode 的 css 校验，可以在设置里面把 `css.validate` 关掉。

**Comment by superlbr** [comment]
可以不改后缀..
```
{
  "overrides": [
    {
      "files": "*.wxml",
      "options": { "parser": "html" }
    }
  ]
}
```

**Comment by yangmingshan** [comment]
默认语法高亮也是个原因。
