### ISSUE TITLE
支持webpack/vite等打包工具

### ISSUE THREAD

**Issue by 9romise** [vue-mini/create-vue-mini#14]
_只是一个想法_
目前新建的模板使用的是build.js，或许可以封装成vite插件？或使用unplugin来一次支持多个打包工具？
在这些打包工具的钩子中或许也可以做更多事

**Comment by yangmingshan** [comment]
webpack/vite 是面向 web 的，并不适用于小程序。当然这是我的看法，如果你认为它们跟小程序可以搭配，欢迎探索并分享你的成果。
