### ISSUE TITLE
使用@vant/area-data的数据编译出错

### ISSUE THREAD

**Issue by MaZhaolin** [vue-mini/create-vue-mini#16]
https://github.com/youzan/vant/tree/main/packages/vant-area-data
<img width="1003" alt="image" src="https://github.com/user-attachments/assets/ceda81b1-f59d-454a-8c3e-b5be26217d39">

**Comment by yangmingshan** [comment]
你使用哪个版本的 `create-vue-mini ` 创建的项目？尝试升级到最新版本试试

**Comment by yangmingshan** [comment]
create-vue-mini v1.2.2 已修复。

**Comment by MaZhaolin** [comment]
我这个项目已经再开发中了，想问下怎么升级呢

**Comment by yangmingshan** [comment]
根据你使用 JS 还是 TS，拷贝对应的文件替换项目的 `build.js`

JS:
https://github.com/vue-mini/create-vue-mini/blob/main/template/javascript/build.js

TS:
https://github.com/vue-mini/create-vue-mini/blob/main/template/typescript/build.js

**Comment by yangmingshan** [comment]
这个问题的本质原因是 @vant/area-data 没有暴露出 package.json，我在 create-vue-mini v1.2.2 尝试做了兼容，但是会造成其他问题（#17），所以兼容已经在 create-vue-mini v1.2.3 被回退了。

这个问题应该推动 @vant/area-data 修改，我已经提交了 PR：https://github.com/youzan/vant/pull/13074

参考：https://github.com/nodejs/node/issues/33460

**Comment by yangmingshan** [comment]
PR 已合并，请升级 @vant/area-data
