### ISSUE TITLE
app.css中import第三方css文件报错

### ISSUE THREAD

**Issue by thoomi2009** [vue-mini/create-vue-mini#18]
src 目录下有 app.css,windi.css文件。app.css文件中
```
@import "windi.css"
```
运行的时候，报错。
```
[ WXSS 文件编译错误] 
path `windi.css` not found from `./app.wxss`.(env: Windows,mp,1.06.2405020; lib: 3.5.6)
```
把windi.css 改为windi.wxss是可以的。但是当windi.css 有更新的时候，页面css加载失败

**Comment by calandnong** [comment]
> src 目录下有 app.css,windi.css文件。app.css文件中
> 
> ```
> @import "windi.css"
> ```
> 
> 运行的时候，报错。
> 
> ```
> [ WXSS 文件编译错误] 
> path `windi.css` not found from `./app.wxss`.(env: Windows,mp,1.06.2405020; lib: 3.5.6)
> ```
> 
> 把windi.css 改为windi.wxss是可以的。但是当windi.css 有更新的时候，页面css加载失败

这里需要自己加一下打包过去，可以参考build.js中app.css的拷贝方式

**Comment by yangmingshan** [comment]
https://github.com/vue-mini/create-vue-mini/releases/tag/1.2.6
