### ISSUE TITLE
最新版本build 完后dist的miniprogram_npm的依赖减少了

### ISSUE THREAD

**Issue by GCM6** [vue-mini/create-vue-mini#24]
**项目能正常run起来，只是依赖少了！**

**1. 这是build 完后得到的依赖**

<img width="382" alt="image" src="https://github.com/user-attachments/assets/4df09032-bf8a-4abf-9a36-565dae21f874">

**2. 这是依赖，而且检查了node_modules中也是有对应的依赖的**

<img width="362" alt="image" src="https://github.com/user-attachments/assets/2bf26d29-8176-40ff-b654-317b4dc3258f">

**3.这是对应的依赖**
  "dependencies": {
    "@babel/runtime": "^7.25.0",
    "@vue-mini/core": "^1.1.0",
    "atomu": "^0.0.5",
    "daigo": "^1.2.0",
    "dayjs": "^1.11.13",
    "miniprogram-api-promise": "^1.0.4",
    "mitt": "^3.0.1",
    "promise-polyfill": "^8.3.0",
    "tdesign-miniprogram": "^1.5.1"
  },
  
  希望获得的结果： 依赖完整copy到miniprogram_npm

**Comment by yangmingshan** [comment]
除 UI Component Library 外，会根据使用情况编译。
