### ISSUE TITLE
在引用 vant-weapp 类原生UI组件时，可以做到按需复制组件库吗？

### ISSUE THREAD

**Issue by watsonhaw5566** [vue-mini/create-vue-mini#25]
杨兄，你好，我又来了。

我在使用 vue-mini 的时候使用带第三方UI库时，发现虽然 vant/weapp/lib 是复制过去了。

但貌似是全量复制过去，这样导致了包体积一下子就涨起来了。

所以想讨论一下有没有好处理办法。

**Comment by yangmingshan** [comment]
小程序打包上传时会排除掉未使用的文件。
