### ISSUE TITLE
npm create vue-mini@latest 报错

### ISSUE THREAD

**Issue by xb001130** [vue-mini/create-vue-mini#3]
![微信截图_20240627095246](https://github.com/vue-mini/create-vue-mini/assets/86430921/65c579c6-fc5b-409a-bc92-34913d61b4e2)

**Comment by xb001130** [comment]
使用nvm控制node版本，nvm安装在D盘，创建项目也在D盘

**Comment by yangmingshan** [comment]
看起来是个比较容易修的问题。但是我手上没有 Windows 电脑。能麻烦你帮忙 debug 一下吗？

把这个仓库下载下来，然后 `pnpm i && pnpm build`，再 `node outfile.js`。使用 node v22.3.0 和 pnpm v9.4.0。

另外你试试跑 `npm create vue@latest` 会有问题吗？

**Comment by xb001130** [comment]
![create-vue-mini](https://github.com/vue-mini/create-vue-mini/assets/86430921/4af46294-08b7-4595-afe3-2473301d1d15)
使用import { fileURLToPath } from 'url'处理路径是可以成功创建项目的，不知道这么处理对不对

**Comment by xb001130** [comment]
```npm create vue@latest```这个命令是没有问题的

**Comment by yangmingshan** [comment]
> 使用import { fileURLToPath } from 'url'处理路径是可以成功创建项目的，不知道这么处理对不对

@xb001130 谢谢，应该就是这个问题。你可以试一下 `npm create vue-mini@0.0.11` 看是不是好了。

**Comment by yangmingshan** [comment]
closed via https://github.com/vue-mini/create-vue-mini/commit/bff58408b52adaf8244c6bc1e5e6ddc424bb0c37
