### ISSUE TITLE
如果 有报错 代码，需要 先把小程序的先关闭。 然后才能重新 运行 启动

### ISSUE THREAD

**Issue by wozhendefuleZ** [vue-mini/create-vue-mini#5]
![微信图片_20240708155235](https://github.com/vue-mini/vue-mini/assets/101495175/70dc7e31-1e26-4dfd-a19a-099470bcab81)

**Comment by yangmingshan** [comment]
你是指如果代码有语法错误，dev server 会崩溃，需要重新启动，是吗？

**Comment by yangmingshan** [comment]
v1.0.1 已修复，现在碰到语法错误 dev server 会报错但不会崩溃退出。等你修好语法错误后 dev server 又会自动继续工作。
