### ISSUE TITLE
创建 vue mini 初始项目报错

### ISSUE THREAD

**Issue by wbxl2000** [vue-mini/create-vue-mini#6]
复现路径：https://vuemini.org/guide/quick-start.html

1. pnpm create vue-mini@latest 一路回车
2. cd vue-mini-project
3. pnpm install
4. pnpm dev

<img width="564" alt="image" src="https://github.com/vue-mini/vue-mini/assets/57169560/4fe1a019-bb46-43e4-80ba-0c6e2e97958a">
<img width="547" alt="image" src="https://github.com/vue-mini/vue-mini/assets/57169560/189f350c-cd9a-4003-a0e4-704e48c5db06">

**Comment by wbxl2000** [comment]
<img width="231" alt="image" src="https://github.com/vue-mini/vue-mini/assets/57169560/96668af6-06be-4cd3-8b46-6ce295bf81ba">

**Comment by yangmingshan** [comment]
请升级你的 node.js 版本，babel.config.js 有用到 import.meta.resolve，node v20.6.0 才开始支持。

**Comment by wbxl2000** [comment]
升级到 v20.15.1 可以了，这里可以考虑写个注意事项，v20.6.0 也挺新的，估计在这个版本之下的也挺多

**Comment by yangmingshan** [comment]
需要做一些修改，更严格的限制用户的 node 版本
